/**
 * Citadao editions raw data.
 * All tuna references use shortName from master-tunas.ts
 * All award references use slug from award-types.ts
 */

export interface CitadaoEditionData {
  edition: number;
  year: number;
  date: string | null;
  venues: string[];
  notes?: string;
  /** Array of tuna shortNames (contestants) */
  tunas: string[];
  /** Array of tuna shortNames (guests) */
  guests: string[];
  /** Map of award slug to winner shortName */
  awards: Record<string, string> | null;
}

export const CITADAO_EDITIONS: CitadaoEditionData[] = [
  {
    edition: 1,
    year: 2004,
    date: '4-5 Novembro',
    venues: ['Aula Magna do IPV'],
    tunas: ['Tuna Peru (Los Andes)', 'Tuna Salamanca', 'TAUE', 'RTUB', 'TMUC'],
    guests: ['Real Tunel', 'Viriatuna', 'Infantuna'],
    awards: null,
  },
  {
    edition: 2,
    year: 2005,
    date: '3-4 Novembro',
    venues: ['Aula Magna do IPV'],
    tunas: ['TMUC', 'Tuna Granada (Loyola)', 'Luz&Tuna', 'Tintuna', 'TABM'],
    guests: ['Infantuna', 'Real Tunel', 'Viriatuna'],
    awards: null,
  },
  {
    edition: 3,
    year: 2007,
    date: '23-24 Marco',
    venues: ['Aula Magna do IPV', 'Forum Viseu'],
    tunas: ['Tuna Granada (Loyola)', 'Tuna UFP', 'Semper Tesus', 'Bruna', 'Tusofona'],
    guests: ['Orfeao Viseu', 'Infantuna', 'Real Tunel', 'Viriatuna'],
    awards: {
      'melhor-tuna': 'Semper Tesus',
      'segunda-melhor-tuna': 'Tuna Granada (Loyola)',
      'melhor-pandeireta': 'Semper Tesus',
      'melhor-instrumental': 'Tuna Granada (Loyola)',
      'melhor-estandarte': 'Semper Tesus',
      'melhor-solista': 'Semper Tesus',
      'melhor-original': 'Tuna UFP',
      'melhor-serenata': 'Semper Tesus',
      'melhor-passacalles': 'Semper Tesus',
      'tuna-mais-tuna': 'Tusofona',
      'tuna-do-publico': 'Semper Tesus',
    },
  },
  {
    edition: 4,
    year: 2008,
    date: '2-3 Maio',
    venues: ['Aula Magna do IPV', 'Rua Formosa'],
    notes: '10o Aniversario da Tunadao 1998',
    tunas: ['Estudantina CB', "Copituna d'Oppidana", 'Semper Tesus', 'TAUP', 'TUSA'],
    guests: ['Charrascos da Citania'],
    awards: null,
  },
  {
    edition: 5,
    year: 2009,
    date: '1-2 Maio',
    venues: ['Aula Magna do IPV', 'Rua Formosa'],
    tunas: ['Hinoportuna', 'Tuna Templaria', 'Imperial Neptuna', 'Estudantina ISEL', 'Afonsina'],
    guests: [],
    awards: {
      'melhor-tuna': 'Hinoportuna',
      'melhor-serenata': 'Tuna Templaria',
      'melhor-solista': 'Imperial Neptuna',
      'melhor-instrumental': 'Hinoportuna',
      'melhor-original': 'Tuna Templaria',
      'melhor-pandeireta': 'Hinoportuna',
      'melhor-estandarte': 'Estudantina ISEL',
      'melhor-passacalles': 'Tuna Templaria',
      'tuna-mais-tuna': 'Afonsina',
    },
  },
  {
    edition: 6,
    year: 2010,
    date: '30 Abril - 1 Maio',
    venues: ['Aula Magna do IPV'],
    tunas: ['anTUNiA', 'Tunideos', 'TUB'],
    guests: ['Cordas ao Cubo'],
    awards: {
      'melhor-tuna': 'anTUNiA',
      'segunda-melhor-tuna': 'Tunideos',
      'tuna-mais-tuna': 'Tunideos',
      'melhor-instrumental': 'Tunideos',
      'melhor-solista': 'anTUNiA',
      'melhor-original': 'Tunideos',
      'melhor-pandeireta': 'anTUNiA',
      'melhor-passacalles': 'Tunideos',
      'melhor-estandarte': 'anTUNiA',
      'melhor-serenata': 'TUB',
    },
  },
  {
    edition: 7,
    year: 2011,
    date: '29-30 Abril',
    venues: ['Aula Magna do IPV', 'Rua Formosa'],
    tunas: ['TMP', 'EUC', 'TUM-Madeira', 'Castra Leuca'],
    guests: ['Orfeao IPV', 'Fado Livre'],
    awards: {
      'melhor-tuna': 'TMP',
      'segunda-melhor-tuna': 'EUC',
      'melhor-serenata': 'EUC',
      'melhor-original': 'TMP',
      'melhor-instrumental': 'EUC',
      'melhor-solista': 'TMP',
      'melhor-pandeireta': 'TMP',
      'melhor-estandarte': 'TUM-Madeira',
      'melhor-passacalles': 'Castra Leuca',
      'tuna-mais-tuna': 'TUM-Madeira',
      'mencao-honrosa': 'Castra Leuca',
    },
  },
  {
    edition: 8,
    year: 2012,
    date: '4-5 Maio',
    venues: ['Aula Magna do IPV', 'Rua Formosa'],
    tunas: ['Desertuna', 'Imperial Neptuna', 'Scalabituna', 'TUCP'],
    guests: ['Orfeao IPV', 'Fado Livre'],
    awards: {
      'melhor-tuna': 'TUCP',
      'tuna-mais-tuna': 'Desertuna',
      'melhor-passacalles': 'Imperial Neptuna',
      'melhor-pandeireta': 'Desertuna',
      'melhor-original': 'Desertuna',
      'melhor-instrumental': 'TUCP',
      'melhor-solista': 'TUCP',
      'melhor-estandarte': 'Scalabituna',
      'melhor-serenata': 'Desertuna',
    },
  },
  {
    edition: 9,
    year: 2013,
    date: '3-4 Maio',
    venues: ['Aula Magna do IPV', 'Rua Formosa'],
    notes: '15 Anos - 1998-2013',
    tunas: ['Luz&Tuna', 'TEUP', 'TUM', 'Magna Tuna Cartola'],
    guests: ['Infantuna', 'Real Tunel'],
    awards: {
      'melhor-tuna': 'Luz&Tuna',
      'tuna-mais-tuna': 'TUM',
      'melhor-passacalles': 'TUM',
      'melhor-pandeireta': 'TEUP',
      'melhor-original': 'Magna Tuna Cartola',
      'melhor-instrumental': 'Luz&Tuna',
      'melhor-solista': 'Luz&Tuna',
      'melhor-estandarte': 'Luz&Tuna',
      'melhor-serenata': 'Luz&Tuna',
    },
  },
  {
    edition: 10,
    year: 2014,
    date: '2-3 Maio',
    venues: ['Aula Magna do IPV', 'Rua Formosa'],
    tunas: ['TDUP', 'TAIPCA', 'TUSA', "Copituna d'Oppidana", 'Tuna Templaria'],
    guests: ['Infantuna', 'Real Tunel'],
    awards: {
      'melhor-tuna': 'TAIPCA',
      'segunda-melhor-tuna': 'TDUP',
      'melhor-original': 'TAIPCA',
      'melhor-instrumental': 'TAIPCA',
      'melhor-solista': 'TDUP',
      'melhor-pandeireta': "Copituna d'Oppidana",
      'melhor-estandarte': 'TDUP',
      'melhor-serenata': "Copituna d'Oppidana",
      'tuna-mais-tuna': 'TUSA',
      'melhor-passacalles': 'TUSA',
    },
  },
  {
    edition: 11,
    year: 2015,
    date: '1-2 Maio',
    venues: ['Aula Magna do IPV', 'Rua Formosa'],
    tunas: ['Afonsina', 'anTUNiA', 'EUL', 'Versus Tuna'],
    guests: ['Infantuna'],
    awards: {
      'melhor-tuna': 'EUL',
      'tuna-mais-tuna': 'Versus Tuna',
      'melhor-solista': 'EUL',
      'melhor-pandeireta': 'Versus Tuna',
      'melhor-passacalles': 'Versus Tuna',
      'melhor-estandarte': 'anTUNiA',
      'melhor-original': 'anTUNiA',
      'melhor-serenata': 'anTUNiA',
      'melhor-instrumental': 'anTUNiA',
    },
  },
  {
    edition: 12,
    year: 2016,
    date: '29-30 Abril',
    venues: ['Aula Magna do IPV', 'Rua Formosa'],
    tunas: ['TMUC', 'TUM', 'EUL', 'Hinoportuna'],
    guests: ['Arfectus'],
    awards: {
      'melhor-tuna': 'TMUC',
      'tuna-mais-tuna': 'TMUC',
      'melhor-passacalles': 'TUM',
      'melhor-serenata': 'TUM',
      'melhor-original': 'TMUC',
      'melhor-instrumental': 'TMUC',
      'melhor-solista': 'EUL',
      'melhor-pandeireta': 'TUM',
      'melhor-estandarte': 'Hinoportuna',
    },
  },
  {
    edition: 13,
    year: 2017,
    date: '5-6 Maio',
    venues: ['Aula Magna do IPV'],
    tunas: ['Azeituna', 'Estudantina CB', 'Luz&Tuna', 'Tunideos'],
    guests: ['Estudantina Lamego', 'Viriatuna'],
    awards: {
      'melhor-tuna': 'Azeituna',
      'tuna-mais-tuna': 'Tunideos',
      'melhor-pandeireta': 'Tunideos',
      'melhor-estandarte': 'Luz&Tuna',
      'melhor-passacalles': 'Tunideos',
      'melhor-instrumental': 'Estudantina CB',
      'melhor-solista': 'Estudantina CB',
      'melhor-original': 'Azeituna',
      'melhor-serenata': 'Tunideos',
    },
  },
  {
    edition: 14,
    year: 2018,
    date: '4-5 Maio',
    venues: ['Clube de Viseu', 'Aula Magna do IPV'],
    notes: '20 Anos - Tunadao Canta',
    tunas: ['Desertuna', 'TAIPCA', 'TUA', 'TUIST'],
    guests: ['Viriatuna', 'Estudantina Lamego'],
    awards: {
      'melhor-tuna': 'Desertuna',
      'tuna-mais-tuna': 'Desertuna',
      'melhor-serenata': 'TAIPCA',
      'melhor-estandarte': 'Desertuna',
      'melhor-pandeireta': 'Desertuna',
      'melhor-solista': 'Desertuna',
      'melhor-instrumental': 'TUIST',
      'melhor-original': 'TAIPCA',
    },
  },
  {
    edition: 15,
    year: 2019,
    date: '3-4 Maio',
    venues: ['Clube de Viseu', 'Aula Magna do IPV'],
    tunas: ['Tuna Granada (Medicina)', 'Tuna-MUs', 'TUCP', 'TUM'],
    guests: ['Estudantina Lamego', 'Viriatuna'],
    awards: {
      'melhor-tuna': 'TUM',
      'tuna-mais-tuna': 'Tuna-MUs',
      'melhor-serenata': 'TUM',
      'melhor-estandarte': 'TUM',
      'melhor-pandeireta': 'Tuna-MUs',
      'melhor-solista': 'TUCP',
      'melhor-instrumental': 'TUM',
      'melhor-original': 'TUM',
    },
  },
  {
    edition: 16,
    year: 2022,
    date: '29-30 Abril',
    venues: [],
    tunas: ['Afonsina', 'TMUC', 'TAFDUP', 'TUM', 'FAN', 'EUL'],
    guests: [],
    awards: {
      'melhor-tuna': 'Afonsina',
      'tuna-mais-tuna': 'Afonsina',
      'tuna-do-publico': 'Afonsina',
      'melhor-serenata': 'TMUC',
      'melhor-estandarte': 'Afonsina',
      'melhor-pandeireta': 'Afonsina',
      'melhor-solista': 'TAFDUP',
      'melhor-instrumental': 'Afonsina',
      'melhor-original': 'Afonsina',
    },
  },
  {
    edition: 17,
    year: 2023,
    date: '5-6 Maio',
    venues: ['Solar Vinhos do Dao', 'Aula Magna do IPV'],
    tunas: ['EUL', 'TUM', 'FAN', 'TUP'],
    guests: ['Viriatuna', 'Estudantina Lamego'],
    awards: {
      'melhor-tuna': 'TUP',
      'tuna-mais-tuna': 'EUL',
      'tuna-do-publico': 'TUP',
      'melhor-serenata': 'TUP',
      'melhor-estandarte': 'EUL',
      'melhor-pandeireta': 'FAN',
      'melhor-solista': 'FAN',
      'melhor-instrumental': 'TUM',
      'melhor-original': 'EUL',
    },
  },
  {
    edition: 18,
    year: 2024,
    date: '4 Maio',
    venues: [],
    tunas: ['Estudantina CB', 'Desertuna', 'TAIPCA', 'Afonsina'],
    guests: ['AlcaTuna'],
    awards: {
      'melhor-tuna': 'Afonsina',
      'tuna-mais-tuna': 'Desertuna',
      'tuna-do-publico': 'Desertuna',
      'melhor-estandarte': 'Afonsina',
      'melhor-pandeireta': 'Afonsina',
      'melhor-solista': 'Afonsina',
      'melhor-instrumental': 'Estudantina CB',
    },
  },
  {
    edition: 19,
    year: 2025,
    date: null,
    venues: [],
    tunas: [],
    guests: [],
    awards: {
      'melhor-tuna': 'anTUNiA',
      'tuna-mais-tuna': 'Versus Tuna',
      'tuna-do-publico': 'Versus Tuna',
      'melhor-serenata': 'anTUNiA',
      'melhor-estandarte': 'TUSA',
      'melhor-pandeireta': 'anTUNiA',
      'melhor-solista': 'Versus Tuna',
      'melhor-instrumental': 'anTUNiA',
      'melhor-original': 'anTUNiA',
    },
  },
];
