/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'award-types': AwardType;
    'citadao-editions': CitadaoEdition;
    'palmares-years': PalmaresYear;
    'blog-posts': BlogPost;
    videos: Video;
    albums: Album;
    pages: Page;
    'contact-submissions': ContactSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'award-types': AwardTypesSelect<false> | AwardTypesSelect<true>;
    'citadao-editions': CitadaoEditionsSelect<false> | CitadaoEditionsSelect<true>;
    'palmares-years': PalmaresYearsSelect<false> | PalmaresYearsSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    albums: AlbumsSelect<false> | AlbumsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'contact-info': ContactInfo;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'contact-info': ContactInfoSelect<false> | ContactInfoSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Texto alternativo para acessibilidade
   */
  alt: string;
  /**
   * Legenda opcional para a imagem
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Tipos de prémios (usados no Citadão e Palmarés)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "award-types".
 */
export interface AwardType {
  id: number;
  /**
   * Nome principal do prémio (ex: Melhor Pandeireta)
   */
  name: string;
  /**
   * Identificador único (ex: melhor-pandeireta)
   */
  slug: string;
  /**
   * Nomes alternativos usados por outros festivais
   */
  aliases?:
    | {
        alias: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Descrição do prémio (aparece em tooltip)
   */
  description?: string | null;
  /**
   * Critérios de avaliação detalhados
   */
  criteria?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Ícone do prémio (emoji ou código)
   */
  icon?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Edições do Festival Citadão
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "citadao-editions".
 */
export interface CitadaoEdition {
  id: number;
  title?: string | null;
  /**
   * Número da edição
   */
  edition: number;
  /**
   * Ano
   */
  year: number;
  /**
   * Data (ex: 4-5 Maio)
   */
  date?: string | null;
  /**
   * Local do evento
   */
  venue?: string | null;
  /**
   * Cartaz do evento
   */
  poster?: (number | null) | Media;
  /**
   * Tunas participantes (a concurso)
   */
  tunas?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Tunas/grupos convidados
   */
  guests?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Prémios atribuídos
   */
  awards?:
    | {
        awardType: number | AwardType;
        /**
         * Nome da tuna vencedora
         */
        winner: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Notas especiais (ex: 10º Aniversário)
   */
  notes?: string | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Prémios ganhos pela Tunadão por ano
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "palmares-years".
 */
export interface PalmaresYear {
  id: number;
  yearTitle?: string | null;
  /**
   * Ano
   */
  year: number;
  /**
   * Festivais onde participámos
   */
  festivals: {
    /**
     * Nome do festival
     */
    name: string;
    /**
     * Localização
     */
    location?: string | null;
    /**
     * Prémios ganhos
     */
    awards?:
      | {
          /**
           * Tipo de prémio (opcional se não existir na lista)
           */
          awardType?: (number | null) | AwardType;
          /**
           * Nome personalizado (se diferente do tipo)
           */
          customName?: string | null;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Artigos do blog
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  /**
   * URL amigável (ex: primeiro-festival-2024)
   */
  slug: string;
  /**
   * Resumo curto para listagens
   */
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  featuredImage: number | Media;
  /**
   * Autor do artigo
   */
  author: number | User;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  publishedAt: string;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Vídeos do YouTube
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  title: string;
  /**
   * URL completo do vídeo (ex: https://youtube.com/watch?v=...)
   */
  youtubeUrl: string;
  youtubeId?: string | null;
  /**
   * Descrição do vídeo
   */
  description?: string | null;
  category: 'atuacao' | 'festival' | 'serenata' | 'citadao' | 'outro';
  /**
   * Mostrar em destaque na página de vídeos
   */
  featured?: boolean | null;
  /**
   * Data de publicação/evento
   */
  publishedAt: string;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Álbuns de música
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "albums".
 */
export interface Album {
  id: number;
  /**
   * Nome do álbum
   */
  title: string;
  /**
   * Ano de lançamento
   */
  year: number;
  /**
   * Capa do álbum
   */
  coverImage: number | Media;
  /**
   * Descrição/história do álbum
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Link para o álbum no Spotify
   */
  spotifyUrl?: string | null;
  /**
   * Lista de faixas
   */
  tracks?:
    | {
        number: number;
        title: string;
        /**
         * Duração (ex: 3:45)
         */
        duration?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Tipo de gravação
   */
  recordingType?: ('live' | 'studio') | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Páginas de conteúdo estático
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL da página (ex: sobre-nos)
   */
  slug: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Título para motores de busca (deixar vazio para usar o título principal)
   */
  seoTitle?: string | null;
  /**
   * Descrição para motores de busca (máx 160 caracteres)
   */
  seoDescription?: string | null;
  /**
   * Imagem para partilha em redes sociais
   */
  seoImage?: (number | null) | Media;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Mensagens recebidas pelo formulário de contacto
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  subject: string;
  message: string;
  status: 'new' | 'read' | 'replied' | 'archived';
  /**
   * Notas internas sobre este contacto
   */
  notes?: string | null;
  honeypot?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'award-types';
        value: number | AwardType;
      } | null)
    | ({
        relationTo: 'citadao-editions';
        value: number | CitadaoEdition;
      } | null)
    | ({
        relationTo: 'palmares-years';
        value: number | PalmaresYear;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'albums';
        value: number | Album;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "award-types_select".
 */
export interface AwardTypesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  aliases?:
    | T
    | {
        alias?: T;
        id?: T;
      };
  description?: T;
  criteria?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "citadao-editions_select".
 */
export interface CitadaoEditionsSelect<T extends boolean = true> {
  title?: T;
  edition?: T;
  year?: T;
  date?: T;
  venue?: T;
  poster?: T;
  tunas?:
    | T
    | {
        name?: T;
        id?: T;
      };
  guests?:
    | T
    | {
        name?: T;
        id?: T;
      };
  awards?:
    | T
    | {
        awardType?: T;
        winner?: T;
        id?: T;
      };
  notes?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "palmares-years_select".
 */
export interface PalmaresYearsSelect<T extends boolean = true> {
  yearTitle?: T;
  year?: T;
  festivals?:
    | T
    | {
        name?: T;
        location?: T;
        awards?:
          | T
          | {
              awardType?: T;
              customName?: T;
              id?: T;
            };
        id?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  author?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  publishedAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  title?: T;
  youtubeUrl?: T;
  youtubeId?: T;
  description?: T;
  category?: T;
  featured?: T;
  publishedAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "albums_select".
 */
export interface AlbumsSelect<T extends boolean = true> {
  title?: T;
  year?: T;
  coverImage?: T;
  description?: T;
  spotifyUrl?: T;
  tracks?:
    | T
    | {
        number?: T;
        title?: T;
        duration?: T;
        id?: T;
      };
  recordingType?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  seoTitle?: T;
  seoDescription?: T;
  seoImage?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  subject?: T;
  message?: T;
  status?: T;
  notes?: T;
  honeypot?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  siteDescription: string;
  logo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  /**
   * URL do Instagram
   */
  instagram?: string | null;
  /**
   * URL do Facebook
   */
  facebook?: string | null;
  /**
   * URL do TikTok
   */
  tiktok?: string | null;
  /**
   * URL do YouTube
   */
  youtube?: string | null;
  /**
   * URL do Spotify
   */
  spotify?: string | null;
  /**
   * Imagem padrão para partilha em redes sociais
   */
  defaultSeoImage?: (number | null) | Media;
  /**
   * Google Analytics ID (ex: G-XXXXXXXXXX)
   */
  googleAnalyticsId?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-info".
 */
export interface ContactInfo {
  id: number;
  email: string;
  phone?: string | null;
  address?: string | null;
  /**
   * URL do Google Maps embed (opcional)
   */
  mapEmbedUrl?: string | null;
  coordinates?: {
    latitude?: number | null;
    longitude?: number | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  logo?: T;
  favicon?: T;
  instagram?: T;
  facebook?: T;
  tiktok?: T;
  youtube?: T;
  spotify?: T;
  defaultSeoImage?: T;
  googleAnalyticsId?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-info_select".
 */
export interface ContactInfoSelect<T extends boolean = true> {
  email?: T;
  phone?: T;
  address?: T;
  mapEmbedUrl?: T;
  coordinates?:
    | T
    | {
        latitude?: T;
        longitude?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}